### 1. Obtener todas las rutinas (Prueba GET)
GET http://localhost:5152/api/routines
Accept: application/json

### 2. Crear una nueva rutina (Prueba POST)
POST http://localhost:5152/api/routines
Content-Type: application/json

{
  "nombre": "Yoga 15 min"
}